### ISSUE TITLE
cordova-android7.0.0集成微博登录，授权后出现闪退

### ISSUE THREAD

**Issue by zhangps110** [iVanPan/cordova_weibo#60]
Process: com.broom.quzhuanpan, PID: 24749
    java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libweibosdkcore.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:42)
        at com.sina.weibo.sdk.net.HttpManager.openUrl(HttpManager.java:62)
        at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:403)
        at com.sina.weibo.sdk.utils.AidTask.access$200(AidTask.java:49)
        at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:235)
        at java.lang.Thread.run(Thread.java:760)

以上是通过android studio截取的错误信息。不知道该怎么解决，求指导！

**Comment by xushuo** [comment]
求解

**Comment by iVanPan** [comment]
https://github.com/sinaweibosdk/weibo_android_sdk/issues/333   麻烦自己Google 一下
